### PR TITLE
PR to bring Dockerfile in line with official ones

### PR DESCRIPTION
**Pull request by CM2Walki**
* Now based on aspnet runtime image not sdk (since there is nothing being built)
* Merged all runs into one to prevent excess layers
* Reduced image size (by removing packages not required for running the bot)
* Made user name & id configurable
* Now installing youtube-dl
* Added reference to port exposing for webapi

### CODE REVIEW

**Comment by s4ke** [comment]
@CM2Walki  What is the current status of youtube-dl drama? I think it is still not resolved, right? I don't want to have any legal issues by having this repository open.

**Comment by CM2Walki** [comment]
I believe it has been resolved. It's back on Github:
https://github.com/ytdl-org/youtube-dl

**Comment by skyfrk** [comment]
Why is this PR not merged yet?

The yt-dl issue has been resolved: https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/

**Comment by s4ke** [comment]
@skyfrk This only concerns the stance that GitHub is taking as far as I can tell. I can't find anything that this case has been settled or resolved.

**Comment by CM2Walki** [comment]
Let me suggest a compromise, that should be fine:

I'll leave pip installed in the image and then call pip to install & update youtube-dl in the `ENTRYPOINT`/`CMD`. That way you would, strictly speaking, not have the youtube-dl in your image, it would be added on first run; It also has the added benefit of keeping it up-to-date.

**Comment by CM2Walki** [comment]
For anyone still following this. I built my fork over at https://hub.docker.com/r/cm2network/ts3audiobot. If you want an image that includes youtube-dl by default.

**Comment by s4ke** [comment]
since youtube-dl was reinstated and this has been silent for a while, I opted to merge #8 instead of this one. The end result is similar.

**Pull request closed without merging**
